// Generated by CoffeeScript 1.10.0
(function() {
  window.DataMap = (function() {
    function DataMap(filename) {
      var image;
      console.log("Loading data map", filename);
      image = new Image();
      image.onload = (function(_this) {
        return function() {
          var canvas, i, imageData, j, ref, ref1, x, y;
          _this.size = image.width;
          canvas = document.createElement('canvas');
          canvas.width = _this.size;
          canvas.height = _this.size;
          canvas.getContext('2d').drawImage(image, 0, 0, _this.size, _this.size);
          imageData = canvas.getContext('2d').getImageData(0, 0, _this.size, _this.size).data;
          _this.data = [];
          for (x = i = 0, ref = _this.size; 0 <= ref ? i < ref : i > ref; x = 0 <= ref ? ++i : --i) {
            _this.data[x] = [];
            for (y = j = 0, ref1 = _this.size; 0 <= ref1 ? j < ref1 : j > ref1; y = 0 <= ref1 ? ++j : --j) {
              _this.data[x][y] = imageData[(y * _this.size + x) * 4] / 255;
            }
          }
          return _this.loaded = true;
        };
      })(this);
      image.src = filename;
    }

    DataMap.prototype.valueAt = function(xPercentage, yPercentage) {
      var x, y;
      if (!this.loaded) {
        return 0;
      }
      x = Math.floor(xPercentage * this.size);
      y = Math.floor(yPercentage * this.size);
      return this.data[x][y];
    };

    return DataMap;

  })();

}).call(this);

//# sourceMappingURL=datamap.js.map
