// Generated by CoffeeScript 1.10.0
(function() {
  window.Gradient = (function() {
    function Gradient(filename) {
      var image;
      console.log("Loading gradient", filename);
      image = new Image();
      image.onload = (function(_this) {
        return function() {
          var b, canvas, g, i, imageData, r, ref, x;
          _this.size = image.width;
          canvas = document.createElement('canvas');
          canvas.width = _this.size;
          canvas.height = 1;
          canvas.getContext('2d').drawImage(image, 0, 0, _this.size, 1);
          imageData = canvas.getContext('2d').getImageData(0, 0, _this.size, 1).data;
          _this.data = [];
          for (x = i = 0, ref = _this.size; 0 <= ref ? i < ref : i > ref; x = 0 <= ref ? ++i : --i) {
            r = imageData[x * 4] / 255;
            g = imageData[x * 4 + 1] / 255;
            b = imageData[x * 4 + 2] / 255;
            _this.data[x] = new THREE.Color(r, g, b);
          }
          return _this.loaded = true;
        };
      })(this);
      image.src = filename;
    }

    Gradient.prototype.colorAt = function(percentage) {
      var x;
      if (!this.loaded) {
        return null;
      }
      x = Math.floor(percentage * this.size);
      return this.data[x];
    };

    return Gradient;

  })();

}).call(this);

//# sourceMappingURL=gradient.js.map
