// Generated by CoffeeScript 1.10.0
(function() {
  window.Ocean = (function() {
    function Ocean(renderer, camera, light, scene, size) {
      var mirrorMesh, waterNormals;
      waterNormals = new THREE.TextureLoader().load('waternormals.jpg');
      waterNormals.wrapS = waterNormals.wrapT = THREE.RepeatWrapping;
      this.water = new THREE.Water(renderer, camera, scene, {
        textureWidth: 1024,
        textureHeight: 1024,
        waterNormals: waterNormals,
        alpha: 0.5,
        sunDirection: light.position.clone().normalize(),
        sunColor: 0xffffff,
        waterColor: 0x070411,
        distortionScale: size * 0.01
      });
      mirrorMesh = new THREE.Mesh(new THREE.PlaneBufferGeometry(size, size), this.water.material);
      mirrorMesh.add(this.water);
      mirrorMesh.rotation.x = -Math.PI * 0.5;
      scene.add(mirrorMesh);
    }

    Ocean.prototype.draw = function() {
      this.water.material.uniforms.time.value += 1.0 / 60.0;
      return this.water.render();
    };

    return Ocean;

  })();

}).call(this);

//# sourceMappingURL=ocean.js.map
